name: Frontend E2E Test

on:
  schedule:
    - cron: '0 3 * * *'      # Corre todos los días a las 3am UTC (10pm Colombia)
  workflow_dispatch:         # Te permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload HTML report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
